### HEROKU TESTS ###

### Get all diecasts
GET https://display-case.herokuapp.com/diecasts
### Get one diecast
GET https://display-case.herokuapp.com/diecasts/628695fcc6e35cafb6ecdf7c
### Create diecast
POST https://display-case.herokuapp.com/diecasts HTTP/1.1
content-type: application/json

{
   "carNumber": "99",
   "make": "Chevrolet",
   "model": "Monte Carlo",
   "year": "1987",
   "scale": "1:24",
   "sponsor": "Yummy Snacks",
   "driverFirst": "Jim-Bob",
   "driverLast": "Johnsonson",
   "imageUrl": ""
}
### Update diecast
PUT https://display-case.herokuapp.com/diecasts/629009b4216a73411e78e960 HTTP/1.1
content-type: application/json

{
   "carNumber": "1",
   "make": "Ford",
   "model": "Thunderbird",
   "year": "1987",
   "scale": "1:24",
   "sponsor": "Disgusting Trash Snacks",
   "driverFirst": "Henry",
   "driverLast": "Dickenson",
   "imageUrl": ""
}
### Delete contact (replace ID)
DELETE https://display-case.herokuapp.com/diecasts/62ae401d65bf4e2670e9c83e HTTP/1.1